# Generated by Django 4.2.7 on 2025-06-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integration",
            name="provider",
            field=models.CharField(
                choices=[
                    ("google_calendar", "Google Calendar"),
                    ("google_gmail", "Gmail"),
                    ("microsoft_calendar", "Microsoft Calendar"),
                    ("microsoft_outlook", "Microsoft Outlook"),
                    ("github", "GitHub"),
                    ("slack", "Slack"),
                    ("calendly", "Calendly"),
                ],
                max_length=50,
            ),
        ),
    ]
